### ISSUE TITLE
Raspbian Wheezy

### ISSUE THREAD

**Issue by nskou** [motske/PowerSwitch3#1]
I am trying to install the Powerswitch III plugin on a raspberry pi 2 running raspbian wheezy but get this error code in the LMS log

[15-09-02 20:17:32.5451] main::init (383) Starting Logitech Media Server (v7.9.0, 1441021628, Tue Sep  1 04:05:03 UTC 2015) perl 5.014002
[15-09-02 20:17:33.1222] Slim::Utils::PluginManager::_parseInstallManifest (671) Warning: Unable to parse XML in file [/usr/share/squeezeboxserver/Plugins/PowerSwitchIII/install.xml]: [
not well-formed (invalid token) at line 33, column 70, byte 2509 at /usr/share/squeezeboxserver/CPAN/XML/Parser.pm line 187

Any advise?

**Comment by Robaird** [comment]
I need to look at install file, as it sounds like it's been corrupted since the file only has 21 lines.  Can you upload the file to some cloud service and post a link in response?  Or you can try taking a screen shot of the contents and upload it here (see instructions below).

**Comment by nskou** [comment]
Hi

Thank you for your reply. The install.xml can be found here
https://www.dropbox.com/s/iotvt1mfum7e14n/install.xml?dl=0

**Comment by Robaird** [comment]
Not sure where that file came from, but it's nothing we created.  Did you click on the "download zip" link on the powerswitch3 github page?  Try again, open up install.xml and compare it to the one on the github page--should only be 21 lines--not hundreds of lines.

**Comment by Robaird** [comment]
Also, note that there is an instructions tab on github as well for using the plugin--you probably already saw it, but just in case....

**Comment by nskou** [comment]
This is very strange. I used wget via ssh to download the files to my raspberry and the install.xml ended up like that. Well, downloaded to a different machine, made sure it looked ok and transferred to my raspberry. Now everything works. Thank you so much!

**Comment by Robaird** [comment]
Glad you got it sorted out--and solved the mystery of the odd install file!
